
version: '2'

services:
  js-starter - react:
    image: js-starter - react:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000